export default {
  SPLASH: 'Splash',
  FRONT: 'Front',
  SIGN_UP: 'SignUp',
  SIGN_IN: 'SignIn',
  PUMPING: 'Pumping',
  PUMPING_MANNUAL: 'PumpingMannual',
  SLEEPING: 'Sleeping',
  SLEEPING_MANNUAL: 'SleepingMannual',
  BREAST: 'Breast',
  BREASTMANNUAL: 'BreastMannual',
  PROFILEPAGE: 'ProfilePage',
  BOTTOM_TABS: 'BottomTabs',
  SETTINGS: 'Settings',
  PROFILE: 'Profile',
  COMMUNITY: 'Community',
  BOTTLE: 'Bottle',
  SOLIDS: 'Solids',
  ADDCHILD: 'AddChild',
  BORNCHILD: 'BornChild',
  NOTBORNCHILD: 'NotBornChild',
  COMMUNITY_FORUM: 'CommunityForum',
  FORUM_ANSWERS: 'ForumAnswers',
};
